In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [5]:
df = pd.read_csv(r"E:\titanic.csv")

In [6]:
print("Original Dataset:")
(df.head())

Original Dataset:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [8]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [9]:
df['Age'].fillna(df['Age'].mean())

0      34.50000
1      47.00000
2      62.00000
3      27.00000
4      22.00000
         ...
413    30.27259
414    39.00000
415    38.50000
416    30.27259
417    30.27259
Name: Age, Length: 418, dtype: float64

In [10]:
df['Fare'] = df['Fare'].fillna(df['Fare'].mean())

In [13]:
df.drop('Cabin',axis=1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,C

In [15]:
le=LabelEncoder()
df['Age']= le.fit_transform(df['Age'])
df['Embarked']= le.fit_transform(df['Embarked'])

In [18]:
scaler= StandardScaler()
df[['Age','Fare']]= scaler.fit_transform(df[['Age','Fare']])

In [19]:
(df.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,-0.108990,0,0,330911,-0.498407,NaN,1
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,0.600081,1,0,363272,-0.513274,NaN,2
2,894,0,2,"Myles, Mr. Thomas Francis",male,1.220519,0,0,240276,-0.465088,NaN,1
3,895,0,3,"Wirz, Mr. Albert",male,-0.552160,0,0,315154,-0.483466,NaN,2
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,-0.862378,1,1,3101298,-0.418471,NaN,2

In [20]:
df.drop('Cabin',axis=1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,0,3,"Kelly, Mr. James",male,-0.108990,0,0,330911,-0.498407,1
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,0.600081,1,0,363272,-0.513274,2
2,894,0,2,"Myles, Mr. Thomas Francis",male,1.220519,0,0,240276,-0.465088,1
3,895,0,3,"Wirz, Mr. Albert",male,-0.552160,0,0,315154,-0.483466,2
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,-0.862378,1,1,3101298,-0.418471,2
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,1.442103,0,0,A.5. 3236,-0.494448,2
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,0.201229,0,0,PC 17758,1.313753,0
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,0.156912,0,0,SOTON/O.Q. 3101262,-0.508792,2
416,1308,0,3,"Ware, Mr. Frederick",male,1.442103,0,0,359309,-0.494448,2
417,1309,0,3,"Peter, Master. Michael J",male,1.442103,1,1,2668,-0.237906,0